version: 2.1
orbs:
  orb-tools: circleci/orb-tools@8.27.3
  sfdx: circleci/salesforce-sfdx@2.0
  slack: circleci/slack@3.4.2
  cypress: cypress-io/cypress@1
jobs:
  install-java:
    # This job installs Java to be used in pmd
    executor: sfdx/default
    steps:
      - checkout
      - run:
          name: Install Java
          command: |
            curl -s "https://get.sdkman.io" | bash
            source "$HOME/.sdkman/bin/sdkman-init.sh"
            sdk install java
  pmd:
    executor: sfdx/default
    steps:
      - checkout
      - run:
          name: Run PMD
          command: |
            curl -L "https://github.com/pmd/pmd/releases/download/pmd_releases/$PMD_VER/$PMD_BIN.zip" -o $PMD_BIN.zip; unzip $PMD_BIN.zip; rm $PMD_BIN.zip;
            $PMD_BIN/bin/run.sh pmd -no-cache -d . -R deploy/ruleset.xml -f text -l apex
  build-dev:
    # This will validate code base to partial
    executor: sfdx/default
    steps:
      - checkout
      - sfdx/install
      - run:
          name: Build
          command: |
            echo $URL > url.txt
            sfdx force:auth:sfdxurl:store -f url.txt -s -a demo.prod
            sfdx force:source:deploy -c -x manifest/package.xml -u demo.prod -l RunLocalTests --ignorewarnings
  cypressrun:
    executor: cypress-io/cypress@1
    steps:
      - run:
        name: CypressTest
        command: |
          npm install
          npm run cy:open:dev
  build-prod:
    # This wil deploy code base to production
    executor: sfdx/default
    steps:
      - checkout
      - sfdx/install
      - run:
          name: Build
          command: |
            echo $URL > url.txt
            sfdx force:auth:sfdxurl:store -f url.txt -s -a demo.prod
            sfdx force:source:deploy -c -x manifest/package.xml -u demo.prod -l RunLocalTests --ignorewarnings
  notify-slack:
    executor: orb-tools/ubuntu
    steps:
      - run: exit 0
      - slack/status:
          fail_only: false
workflows:
  version: 2.1
  test_and_static:
    jobs:
      # - install-java
      # - pmd
      - build-dev
      - cypressrun