version: 2.1
orbs:
  node: circleci/node@3.0.0
jobs: 
  install-cypress:
    steps:
      - run: sudo apt-get install libxtst6 libgconf-2-4 libnss3 libasound2 libgtk-3-0 libxss1
  run-cypress:
    steps:
      - run: npm install
      - run: npm run e2e
workflows:
  version: 2.1
  test_and_static:
    jobs:
        - install-cypress
        - run-cypress:
            requires: 
              - install-cypress
      